amnion_version: "1.0.0"
routes:
    root:
      meta:
        title: CNXT | Dynamic Namespaces
        description: >-
          Dynamic namespaces for dynamic content. Developed by Bresnow for
          FLTNGMMTH + XDesk
        author: Bresnow
        keywords: 
          - cnxt
          - xdesk
          - dynamic
          - namespaces
          - globalIcon
          - taglish
          - hashtag
          - domains
          - crypto
          - floating
          - mammoth
          - FLTNGMMTH
          - Bresnow
          - development
          - server
          - Remix.run
          - GunDB
          - gun
        og:type: website
        og:image:  https://cnxt.dev/images/x_icon.png
        og:image:width: 512
        og:image:height: 512
        og:description: Dynamic namespaces for dynamic content. \#://HashtagProtocol
        og:title: Dynamic Namespaces
        og:url: https://cnxt.dev 
        og:site_name: 
        og:locale: en_US
        twitter:card: summary_large_image
        twitter:site: \@bresnow
        twitter:creator: \@bresnow
        twitter:title:  Dynamic Namespaces
        twitter:description: Dynamic namespaces for dynamic content. \#://HashtagProtocol
        twitter:image: https://cnxt.dev/images/x_icon.png
        twitter:image:alt: CNXT | Dynamic Namespaces
        twitter:image:width: 512
        twitter:image:height: 512


    explore:
      header:
        title: CNXT
        subtitle: Alpha implementation of the \#HashedTagNamespaceProtocol
      heading: CNXT  Dynamic Namespaces
      profile: /images/AppIcon.svg
      text: >-
        #://CNXT [pronounced "connects"] is a asset issuance protocol that uses
        cryptographically "Hashed Tags" as content addresses to create and store
        entire platforms, aka #://Namespaces, on a public ledger. While the 
        ledger tokenizes the Namespaces per se, the data that gives the platform 
        it's value is encrypted and persisted locally within your browser.
                
      meta_cards:
        service_delimiters:
          - hash:
              prefix: \#
              service: Information Delimiter
              description: Point to any information. The default delimiter.
          - at:
              prefix: \@
              service: Identity Delimiter
              description: >-
              User profiles, resumes, #eBusinessCards, and namespaces
              identifying individual personalities.
          - dollar:
              prefix: \$
              service: Finance & Barter Delimiter
              description: >-
              Price tickers, ecommerce, cryptocurrency, coupons, etc. The
              default delimiter for namespaces about money.
          - alert:
              prefix: \!
              service: Alert Delimiter
              description: >-
              Messages, notifications, chat, etc... The default delimiter for
              building namespaces around communication awareness.
          - wildcard:
              prefix: \*
              service: WildCard Delimiter
              description: Namespaces dealing with more than one hash service.
        links:
          github:
            id: github-remix.gun
            link: https://github.com/bresnow/remix.gun/tree/cnxt
            label: Github
          twitter:
            id: github-remix.gun
            link: https://github.com/bresnow/remix.gun/tree/cnxt
            label: Github
