version: "3.9"

services:
  amnion_development:
    image: bresnow/amnion-dev:${VERSION:-latest}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-net
        - traefik.constraint-label=traefik-net
        - traefik.http.routers.proxy-${ID:-xdesk_dev}.rule=Host(`${DOMAIN:-cnxt.dev}`)
        - traefik.http.routers.proxy-${ID:-xdesk_dev}.entrypoints=http,https
        - traefik.http.routers.proxy-${ID:-xdesk_dev}.service=proxy-${ID:-xdesk_dev}
        - traefik.http.routers.proxy-${ID:-xdesk_dev}.tls=true
        - traefik.http.routers.proxy-${ID:-xdesk_dev}.tls.certresolver=${TLS:-letsencrypt}
        - traefik.http.services.proxy-${ID:-xdesk_dev}.loadbalancer.server.port=${FRONTEND_PORT:-3333}
        - traefik.http.routers.gjsx-${ID:-xdesk_dev}.rule=Host(`${INTERFACE_DOMAIN:-namespace.cnxt.dev}`)
        - traefik.http.routers.gjsx-${ID:-xdesk_dev}.entrypoints=http,https
        - traefik.http.routers.gjsx-${ID:-xdesk_dev}.service=gjsx-${ID:-xdesk_dev}
        - traefik.http.routers.gjsx-${ID:-xdesk_dev}.tls=true
        - traefik.http.routers.gjsx-${ID:-xdesk_dev}.tls.certresolver=${TLS:-letsencrypt}
        - traefik.http.services.gjsx-${ID:-xdesk_dev}.loadbalancer.server.port=8086
        - traefik.http.routers.internal_socket-${ID:-xdesk_dev}.rule=Host(`${PEER_SOCKET_DOMAIN:-peer-internal.cnxt.dev}`)
        - traefik.http.routers.internal_socket-${ID:-xdesk_dev}.entrypoints=http,https
        - traefik.http.routers.internal_socket-${ID:-xdesk_dev}.service=internal_socket-${ID:-xdesk_dev}
        - traefik.http.routers.internal_socket-${ID:-xdesk_dev}.tls=true
        - traefik.http.routers.internal_socket-${ID:-xdesk_dev}.tls.certresolver=${TLS:-letsencrypt}
        - traefik.http.services.internal_socket-${ID:-xdesk_dev}.loadbalancer.server.port=${PEER_SOCKET_PORT:-8088}
    networks:
      - traefik-net
      - socket-proxy
    volumes:
      - project:/gjsx
      - app_data:/data
      - dev_dri:/dev/dri
      - logs:/var/log
      - /home/administrator/app.xdesk/docker/supervisor/dev:/etc/supervisord
    environment:
      C99_API_KEY: ${C99_API_KEY}
      SERVICE_NAME: "{{.Service.Name}}"
      PEER_SOCKET_DOMAIN: ${PEER_SOCKET_DOMAIN:-peer-internal.cnxt.dev}
      DOMAIN: ${DOMAIN:-cnxt.dev}
      INTERFACE_DOMAIN: ${INTERFACE_DOMAIN:-namespace.cnxt.dev}
      STRIPE_SECRET_KEY: ${STRIPE_SECRECT_KEY}
      STRIPE_CONNECT_CLIENT_ID: ${STRIPE_CONNECT_CLIENT_ID}
      ISSUER_ID: ${ISSUER_ID}
      ISSUER_SEED: ${ISSUER_SEED}
      HORIZON_URL: ${HORIZON_URL:-https://horizon-testnet.cnxt.dev}
      NETWORK_PASSPHRASE: ${NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}
      WITHDRAW_ENDPOINT: ${WITHDRAW_ENDPOINT:-http://0.0.0.0:3333/api/withdraw}

volumes:
  project:
    driver: local-persist
    driver_opts:
      mountpoint: ${project_mountpoint:-/home/administrator/app.xdesk}
  app_data:
    driver: local-persist
    driver_opts:
      mountpoint: ${app_data_mountpoint:-/home/administrator/volumes/drive.cnxt.app/appdata}
  dev_dri:
    external: true
  logs:
    driver: local-persist
    driver_opts:
      mountpoint: ${LOGS_PATH:-/home/administrator/app.xdesk/.logs/dev}

networks:
  traefik-net:
    external: true
  socket-proxy:
    external: true